### ISSUE TITLE
Feature request: Option to generate an enum containing table names

### ISSUE THREAD

**Issue by TimMikeladze** [rmp135/sql-ts#113]
It would be useful to also generate a typescript enum containing the names of all the tables that were used to generate the types.

If you're open to this idea, I can look into implementing it and sending a PR.

**Comment by TimMikeladze** [comment]
Follow up for anyone who is looking to achieve something similar. I was able to get this working locally by using a custom template in my config. I copied the default template and then added the following to it:

```
export enum Tables {
{{#each tables as |table|}}
  {{ table.name }} = '{{ table.name }}',
{{/each}}
}
```

**Comment by ivanhofer** [comment]
@TimMikeladze thank you! I was exactly looking for this.

**Comment by rmp135** [comment]
I think this is too bespoke for this project and I won't be adding it as standard functionality, but glad you found a solution.

I am curious though, what was the reasoning behind wanting a list of table enums?

**Comment by ivanhofer** [comment]
> I am curious though, what was the reasoning behind wanting a list of table enums?

I use it to let `TypeScript` remind me to define some test data whenever a new table gets added to the database:

```ts
const testDataMap: Record<Tables, ((sql: postgres.Sql) => Promise<void>)> = {
	regions: insertRegionsTestData,
	vendors: insertVendorsTestData,
	...
}
```

When I forgot to specify test data for a table inside `testDataMap`, I'll get an error.

Another use case is to have e.g. a properly typed function that does some operations on a table:
```ts
const clearTable = (tableName: Tables) => ... 
```
By using the `Tables` enum instead of `string` you will immediately catch typos when you accidentially call the function with `'regoins'` instead of `'regions'`.
