### ISSUE TITLE
Support for ENUMs

### ISSUE THREAD

**Issue by tkalliom** [rmp135/sql-ts#36]
Although not a part of the SQL standard, enumerated values are a common feature in domain models, are supported in some ways by most databases, and can be expressed with the TypeScript typing system. Enums in databases currently supported by `sql-ts` come at least in three forms:

1. The PostgreSQL `TYPE ... AS ENUM`, which is a named, stand-alone data type that can be shared by multiple columns in different tables. This pretty clearly maps to a TypeScript string enum, which can then be referred to in the individual table interfaces.
2. The MySQL `ENUM(...)` column type, which is anonymous. It is conceptually similar to a TypeScript string union (`ENUM('a', 'b', 'c') -> 'a' | 'b' | 'c'`), but perhaps using a string enum for these as well would be desirable for consistency?
3. Using a check constraint to limit the column to certain values – the only enum implementation available for SQL Server and SQLite, and preferred by some with PostgreSQL. I don’t know if handling these would be feasible, as check constraints are a very expressive construct, and detecting whether one is to be considered an “enum” or not would probably be difficult.

**Comment by rmp135** [comment]
It's something I've wanted to implement for a while.  PostgreSQL and MySQL can be done with enums, the single use MySQL enums aren't great but they still work. The PostgreSQL naming can come from the  definition, MySQL would have to be `{table}{column}Enum` or something similar.

The way I use enums in other dbs is by using a table as the enum definition. The primary key becomes the value and another column becomes the key. Any column that foreign keys to this table becomes an enum. I didn't know how widespread this is which is why it was never included.

**Comment by daniellemburgLWT** [comment]
Hey @rmp135, have you given any more thought to supporting this?

**Comment by rmp135** [comment]
I can take another look. Are you looking for support for a specific database engine?

**Comment by daniellemburgLWT** [comment]
Yeah, I am specifically targeting Postgres. How much work do you think this would take?

**Comment by rmp135** [comment]
ENUM support for Postgres has been added to 1.5.0. I don't have a lot of experience with Postgres but I've think I got it working. If you reference an ENUM in a different schema or if multiple exist with the same name, use the `schemaAsNamespace` config option.

I may implement MySQL ENUMs as string unions as was suggested in the original ticket if there's more interest.

**Comment by daniellemburgLWT** [comment]
Awesome. Thanks alot!
