### ISSUE TITLE
The user `typeMap` config should override the global `TypeMap`

### ISSUE THREAD

**Issue by ctcarton** [rmp135/sql-ts#57]
If the global map has a type that I want to override then there is no way for me to do that.

**Comment by rmp135** [comment]
I've just tested it and it works as intended. The type on the left is the javascript type and the type in the array is from the database.

For example, to convert all `integer` database types to string (instead of number) you would do.

```json
{
  "typeMap": {
    "string": ["integer"]
  }
}
```

This will override the global type map but not the column specific type overrides.

Let me know if you're still having issues.

**Comment by ctcarton** [comment]
Ok, my mistake. I had a problem with my config. Thanks.
